version: '3'
services:
  prometheus:
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    privileged: true
    image: prom/prometheus:v2.48.0
    ports:
      - '9090:9090'
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prom_data:/prometheus

  grafana:
    container_name: grafana
    privileged: true
    image:  grafana/grafana
    ports:
      - '3000:3000'
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=grafana
    volumes:
      - ./grafana:/etc/grafana/provisioning/datasources

volumes:
  prom_data: